import React from 'react'
import { Header } from '@/components/index';
import "@/styles/globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-decorative">
        <header >
        <Header />
        </header>
        <main >
          {children}
        </main>
        <footer>
          {/* <Footer/> */}
        </footer>
      </body>
    </html>
  );
}
